Language agnostic additional data types
AEVI-AppFlow/pos-android-sdk pull request #238
Opened 2021-06-11 10:39 UTC by GregHib

2021-06-11 10:48 UTC, brettwold requested changes

2021-06-11 10:48 UTC, brettwold commented on flow-base-api/src/main/java/com/aevi/sdk/flow/model/AdditionalData.java
> +            case "Byte":
lets make these lower case please to be consistent

2021-06-11 10:48 UTC, brettwold commented on flow-base-api/src/main/java/com/aevi/sdk/flow/model/AdditionalData.java
> +            case "Byte":
Also should be statics somewhere

2021-06-11 10:50 UTC, brettwold reviewed
Ah, this reminds me... we need to get rid of the double data object structure in here too if possible

2021-06-11 13:37 UTC, GregHib commented
> Ah, this reminds me... we need to get rid of the double data object structure in here too if possible

Not without keeping backwards compatibility that I can see 🙁 

Ways I looked at doing it:

# 1

Serialize/deserialize the map directly and un/wrap manually in to/fromJson
Would require a new JsonConverter method which accepts a gson TypeToken to allow deserializing a map (exposes gson)
Wouldn't be easily be able to keep backwards compatibility; could deserialize as a JsonElement first to check if it has the data field and re-call and wrap when appropriate or trying and falling back after an exception. 🤮 

# 2

Hide the data field using `@Expose` and add a getter with `@JsonConverter.ExposeMethod(value = "")` and tweak ExposedMethod to add fields to the parent element.

However for `@Expose` to work gson requires `excludeFieldsWithoutExposeAnnotation` added to the builder, meaning all other fields would need to be marked with `@Expose` as well, which would also break backwards compatibility.

# 3

Switch Gson for Jackson and use the nice and easy `@JsonUnwrap` 😄 
But that'd break all the existing annotations 🤦

2021-06-15 09:14 UTC, GregHib commented
The problem with using just JSON types is anyone currently storing & retriving an integer (or similar) with the auto-casting `Object getValue(String, Object...)`, switching to a version that seralizes that as a "number" type will fail to deserialize trying to cast it from Double to Int. It can be fixed switching to the generic type method but it'd be a breaking change none-the-less

2021-12-08 14:37 UTC, closed without merging